/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciiIndexRouteImport } from './routes/servicii.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServiciiSlugRouteImport } from './routes/servicii.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciiIndexRoute = ServiciiIndexRouteImport.update({
  id: '/servicii/',
  path: '/servicii/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciiSlugRoute = ServiciiSlugRouteImport.update({
  id: '/servicii/$slug',
  path: '/servicii/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicii/$slug': typeof ServiciiSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/servicii/': typeof ServiciiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicii/$slug': typeof ServiciiSlugRoute
  '/blog': typeof BlogIndexRoute
  '/servicii': typeof ServiciiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicii/$slug': typeof ServiciiSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/servicii/': typeof ServiciiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/servicii/$slug'
    | '/blog/'
    | '/servicii/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/servicii/$slug'
    | '/blog'
    | '/servicii'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/servicii/$slug'
    | '/blog/'
    | '/servicii/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ServiciiSlugRoute: typeof ServiciiSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServiciiIndexRoute: typeof ServiciiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicii/': {
      id: '/servicii/'
      path: '/servicii'
      fullPath: '/servicii/'
      preLoaderRoute: typeof ServiciiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicii/$slug': {
      id: '/servicii/$slug'
      path: '/servicii/$slug'
      fullPath: '/servicii/$slug'
      preLoaderRoute: typeof ServiciiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  ServiciiSlugRoute: ServiciiSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServiciiIndexRoute: ServiciiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
